import { Dancing_Script, Geist, Italianno, Playfair_Display } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const italiano = Italianno({
  variable: "--font-italiano", // ✅ removed extra space
  weight:"400",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: "400",
  subsets: ["latin"],
});

 const dancing = Dancing_Script({
  variable: "--font-dancing",
  weight: "400",
  subsets: ["latin"]
 })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${geistSans.variable} ${italiano.variable} ${playfair.variable} ${dancing.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
          
        </body>
      </html>
    </ClerkProvider>
  );
}